name: WakaTime stat update in README.md
# Please visit https://github.com/avinal/Profile-Readme-WakaTime to setup your own action
on:
  schedule:
    # Runs at 12 am UTC
    - cron: '1 0 * * *'

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
